import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
const server=await createServer({configFile:false,root,resolve:{alias:{'@':root}},server:{middlewareMode:true},appType:'custom'});
try{
 const {emptyState,migrate,load,STORAGE_KEY}=await server.ssrLoadModule('/hooks/useCamelliaStore.ts');
 const {currentAge,profileComplete}=await server.ssrLoadModule('/lib/profile.ts');
 const {restoreArchive,hasPersonalData}=await server.ssrLoadModule('/lib/schoolpark/restore.ts');
 const {mapCamelliaState}=await server.ssrLoadModule('/lib/schoolpark/map.ts');
 const now=new Date('2026-10-06T15:00:00Z');
 assert.equal(currentAge('2008-10-07',now),18);assert.equal(currentAge('2008-10-07',new Date(now.getTime()-1)),17);
 assert.equal(currentAge('1980-10-07',now),46);assert.equal(currentAge('1980-10-07',new Date(now.getTime()-1)),45);
 for(const invalid of ['2026-02-30','2100-01-01','bad'])assert.equal(currentAge(invalid,now),undefined);
 const state=emptyState();state.profile={...state.profile,name:'Synthetic user',birthDate:'2000-10-07',womenServiceAcknowledged:true,agreedAt:'2026-10-01T00:00:00Z'};assert.ok(profileComplete(state.profile,now));
 const at='2026-10-01T00:00:00Z';
 state.checkins=[{id:'check',mood:3,sleep:0,periodDays:0,createdAt:at,updatedAt:at}];
 state.actions=[{id:'action',actionId:'music',title:'Music',category:'PLAY',status:'completed',createdAt:at,updatedAt:at}];
 state.actionFeedback=[{id:'feedback',actionRecordId:'action',actionId:'music',rating:'great',createdAt:at,updatedAt:at}];
 state.savedActions=[{id:'save',actionId:'music',timing:'save_only',createdAt:at,updatedAt:at}];
 state.aiConversations=[{id:'chat',messages:[{id:'msg',role:'user',text:'synthetic text',createdAt:at}],createdAt:at,updatedAt:at}];
 state.contextualMemory=[{id:'ctx',actionId:'music',event:'completed',context:{timeBand:'昼',weekday:1,lifestyle:''},createdAt:at}];
 state.personalMemories=[{id:'mem',text:'',status:'removed',source:'explicit_conversation',createdAt:at,updatedAt:at}];
 state.insights=[{id:'insight',key:'key',text:'pattern',confidence:.7,sampleSize:4,createdAt:at,updatedAt:at}];
 state.insightFeedback=[{id:'if',insightKey:'key',verdict:'incorrect',createdAt:at,updatedAt:at}];
 state.fortunes=[{date:'2026-10-01',cardId:'card',orientation:'upright',status:'drawn',createdAt:at,updatedAt:at}];
 state.treeLeaves=[{id:'leaf',name:'person',category:'friend',meaningTags:[],note:'note',status:'memory',reflections:[],createdAt:at,updatedAt:at}];
 state.analyticsEvents=[{id:'event',name:'check_complete',createdAt:at}];
 const archive=mapCamelliaState(state).filter(x=>x.path.startsWith('imports/')).map(x=>x.data);
 const restored=restoreArchive(archive,emptyState());
 for(const key of ['profile','checkins','actions','actionFeedback','savedActions','aiConversations','contextualMemory','personalMemories','insights','insightFeedback','fortunes','treeLeaves'])assert.deepEqual(restored[key],state[key],key);
 assert.equal(restored.analyticsEvents[0].forwardedAt,at,'restored historic analytics not re-sent');
 assert.throws(()=>restoreArchive(archive.filter(x=>x.kind!=='checkin'),emptyState()),/INCOMPLETE/,'missing archive record cannot silently erase history');
 const stale={...archive.find(x=>x.kind==='checkin'),archiveKey:'checkin-old',content:JSON.stringify({...state.checkins[0],id:'old'})};
 assert.deepEqual(restoreArchive([...archive,stale],emptyState()).checkins,state.checkins,'old unreferenced records do not return');
 assert.throws(()=>mapCamelliaState({...state,aiConversations:[{...state.aiConversations[0],messages:[{...state.aiConversations[0].messages[0],text:'あ'.repeat(240000)}]}]}),/TOO_LARGE/);
 assert.throws(()=>restoreArchive(archive.map(x=>x.kind==='checkin'?{...x,truncated:true}:x),emptyState()),/INCOMPLETE/);
 assert.throws(()=>restoreArchive(archive.filter(x=>x.kind!=='meta'),emptyState()),/INCOMPLETE/);
 const malformed=archive.map(x=>x.kind==='conversation'?{...x,content:JSON.stringify({id:'bad',createdAt:at,messages:[{role:'user'}]})}:x);
 assert.throws(()=>restoreArchive(malformed,emptyState()),/CONVERSATION_INVALID/);
 assert.equal(restoreArchive([{source:'other',content:'bad'}],emptyState()),null);
 const migrated=migrate({...state,version:2});for(const key of Object.keys(state))assert.deepEqual(migrated[key],state[key],key);
 const empty=emptyState();empty.profile.lifestyle='private';assert.ok(hasPersonalData(empty));
 const data=new Map([[STORAGE_KEY,'{invalid']]);globalThis.window={};globalThis.localStorage={getItem:key=>data.get(key)??null};assert.throws(load,/LOCAL_DATA_UNREADABLE/);assert.equal(data.get(STORAGE_KEY),'{invalid');
 delete globalThis.window;delete globalThis.localStorage;
 console.log('Profile/archive: PASS (JST ages, account gate, all beta arrays, remote round-trip, tombstones, corrupt/truncated records preserved by refusal). Firestore delivery is not tested here.');
}finally{await server.close();}
