'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Bell, BookOpen, Check, ChevronLeft, ChevronRight, Clock, Heart, Home, MapPin, MessageCircle, Search, Send, Settings, Sparkles, Star, UserRound, Wind, X } from 'lucide-react';

declare global { interface Document { modelContext?: { registerTool(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options?:{signal?:AbortSignal}):void|Promise<void> } } }

type Tab = 'Today'|'Check'|'AI'|'Discover'|'Circle'|'Place';
type Checkin = { mood:number; sleep:number; condition:string; stress:string; period:string };
type Profile = { name:string; age:string; interests:string[]; lifestyle:string; periodEnabled:boolean; priority:string };
type Chat = { from:'me'|'ai'; text:string };
type DiscoverItem = { id:number; title:string; category:string; minutes:string; image:string; description:string; reason:string };

const NAV:{label:Tab;icon:typeof Home}[]=[{label:'Today',icon:Home},{label:'Check',icon:Heart},{label:'AI',icon:Sparkles},{label:'Discover',icon:Search},{label:'Circle',icon:UserRound},{label:'Place',icon:MapPin}];
const actions=[{label:'整える',icon:Wind,tint:'mint'},{label:'楽しむ',icon:Sparkles,tint:'lavender'},{label:'話す',icon:MessageCircle,tint:'pink'},{label:'学ぶ',icon:BookOpen,tint:'peach'},{label:'休む',icon:Heart,tint:'cream'}];
const discover:DiscoverItem[]=[
 {id:1,title:'からだをほどく、やさしいストレッチ',category:'整える',minutes:'5分',image:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=500&q=80',description:'呼吸に合わせて肩と背中をゆっくり動かす、椅子でもできる短いストレッチです。',reason:'少し疲れを感じている今日に、無理なく切り替えの時間を作れます。'},
 {id:2,title:'鉄分を意識した、かんたん夜ごはん',category:'食事',minutes:'15分',image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=500&q=80',description:'小松菜と豆、卵を使ったやさしい味のワンプレート。',reason:'忙しい日にも手早く、からだをいたわる栄養をとれます。'},
 {id:3,title:'10分だけ、眠くなる読書タイム',category:'休む',minutes:'10分',image:'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=500&q=80',description:'照明を少し落として、通知を切り、本を数ページだけ。',reason:'睡眠時間が短めの今日に、自然な入眠の準備になります。'},
 {id:4,title:'近くのヘッドスパで深呼吸',category:'美容',minutes:'60分',image:'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=500&q=80',description:'渋谷で受けられる、アロマを使ったゆったりヘッドスパ。',reason:'自分では気づきにくい頭や首の緊張を休ませられます。'},
 {id:5,title:'好きな曲を1曲だけ聴く',category:'楽しむ',minutes:'5分',image:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=500&q=80',description:'お気に入りの一曲に、ほかのことをせず耳を傾ける時間。',reason:'気分を軽く切り替えたいときにぴったりです。'},
 {id:6,title:'小さな学びをノートに残す',category:'学ぶ',minutes:'10分',image:'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=500&q=80',description:'気になっていたテーマをひとつ調べ、3行だけメモします。',reason:'達成感を求めすぎず、好奇心を満たせます。'},
 {id:7,title:'朝の光を浴びて散歩する',category:'運動',minutes:'15分',image:'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=500&q=80',description:'歩幅は小さくて大丈夫。近所を気持ちよく歩きます。',reason:'体内リズムと気分をやさしく整えます。'},
];
const circleSeed=[
 {id:1,icon:'🌿',name:'30代のこれから',members:'1,842人',desc:'仕事も暮らしも、自分らしい選択を話そう'},
 {id:2,icon:'🧴',name:'美容・スキンケア',members:'2,345人',desc:'大人肌のケアを気軽にシェア'},
 {id:3,icon:'📚',name:'読書女子',members:'654人',desc:'次に読みたい一冊が見つかる場所'},
 {id:4,icon:'🌙',name:'睡眠を整えたい',members:'987人',desc:'心地よい夜の習慣を交換しよう'},
 {id:5,icon:'🎵',name:'推し活ライフ',members:'1,876人',desc:'好きの力で毎日をもっと楽しく'},
];
const places=[
 {id:1,name:'CAMELLIA YOGA',cat:'運動',sub:'ヨガ・ピラティス',walk:'徒歩5分',rating:'4.8',price:'¥2,500〜',hours:'7:00–21:00',image:'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80'},
 {id:2,name:'温活サロン kokoro',cat:'リラックス',sub:'よもぎ蒸し・温活',walk:'徒歩7分',rating:'4.7',price:'¥4,800〜',hours:'10:00–20:00',image:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80'},
 {id:3,name:'Cafe Camellia',cat:'カフェ',sub:'カフェ・ヘルシーランチ',walk:'徒歩3分',rating:'4.6',price:'¥1,200〜',hours:'8:00–19:00',image:'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80'},
 {id:4,name:'mellow skin room',cat:'美容',sub:'フェイシャルケア',walk:'徒歩9分',rating:'4.9',price:'¥6,600〜',hours:'11:00–20:00',image:'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80'},
];
const STORAGE='camellia-prototype-v1';

function Modal({children,onClose}: {children:React.ReactNode;onClose:()=>void}) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose} aria-label="閉じる"><X/></button>{children}</div></div> }

export default function HomePage(){
 const [ready,setReady]=useState(false); const [tab,setTab]=useState<Tab>('Today');
 const [checkin,setCheckin]=useState<Checkin>({mood:3,sleep:6.25,condition:'疲れ気味',stress:'やや高い',period:'予定まで6日'});
 const [profile,setProfile]=useState<Profile>({name:'さくら',age:'30代',interests:['美容','健康','学び'],lifestyle:'会社員',periodEnabled:true,priority:'休む時間'});
 const [onboarding,setOnboarding]=useState(0); const [settings,setSettings]=useState<'menu'|'profile'|'pricing'|null>(null); const [toast,setToast]=useState('');
 const [category,setCategory]=useState('すべて'); const [detail,setDetail]=useState<DiscoverItem|null>(null); const [done,setDone]=useState<string[]>([]);
 const [joined,setJoined]=useState<number[]>([]); const [circle,setCircle]=useState<number|null>(null); const [likes,setLikes]=useState<number[]>([]); const [posts,setPosts]=useState(['今日は仕事終わりにヨガへ。深呼吸できました🧘','最近、夜は照明を暗くして睡眠改善中です','乾燥する季節のおすすめスキンケアありますか？']); const [postText,setPostText]=useState('');
 const [placeCat,setPlaceCat]=useState('すべて'); const [place,setPlace]=useState<typeof places[number]|null>(null);
 const [chats,setChats]=useState<Chat[]>([{from:'ai',text:'こんばんは、さくらさん🌸\n今の気持ちや、気になっていることを聞かせてください。'}]); const [chatText,setChatText]=useState('');
 useEffect(()=>{ try{const raw=localStorage.getItem(STORAGE); if(raw){const s=JSON.parse(raw); if(s.checkin)setCheckin(s.checkin);if(s.profile)setProfile(s.profile);if(s.done)setDone(s.done);if(s.joined)setJoined(s.joined);if(s.posts)setPosts(s.posts);if(s.seen)setOnboarding(3)} }catch{} setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORAGE,JSON.stringify({checkin,profile,done,joined,posts,seen:onboarding>=3}))},[ready,checkin,profile,done,joined,posts,onboarding]);
 useEffect(()=>{const ctx=document.modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(ctx.registerTool({name:'record_daily_checkin',title:'今日の状態を記録',description:'Camelliaに今日の気分・睡眠・体調・ストレスを記録し、Today画面へ反映します。',inputSchema:{type:'object',properties:{mood:{type:'integer',minimum:1,maximum:5},sleep:{type:'number',minimum:3,maximum:10},condition:{type:'string',enum:['良い','普通','疲れ気味','悪い']},stress:{type:'string',enum:['低い','普通','やや高い','高い']}},required:['mood','sleep','condition','stress'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const x=input as Partial<Checkin>;if(!Number.isInteger(x.mood)||Number(x.mood)<1||Number(x.mood)>5||typeof x.sleep!=='number'||x.sleep<3||x.sleep>10||!['良い','普通','疲れ気味','悪い'].includes(String(x.condition))||!['低い','普通','やや高い','高い'].includes(String(x.stress)))throw new Error('入力値が範囲外です');const next={...checkin,mood:x.mood!,sleep:x.sleep,condition:x.condition!,stress:x.stress!};setCheckin(next);setTab('Today');return{status:'saved',checkin:next}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[checkin]);
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2200)};
 const moodText=['','つらい','少しつらい','普通','良い','とても良い'][checkin.mood];
 const go=(next:Tab)=>{setTab(next);window.scrollTo({top:0,behavior:'smooth'})};
 const sendChat=(text=chatText)=>{if(!text.trim())return; const q=text.trim(); setChats(v=>[...v,{from:'me',text:q}]); setChatText(''); setTimeout(()=>setChats(v=>[...v,{from:'ai',text:reply(q,checkin)}]),350)};
 const filtered=useMemo(()=>category==='すべて'?discover:discover.filter(x=>x.category===category),[category]);
 if(!ready)return null;
 return <main className="stage"><section className="phone-shell">
  {onboarding<3&&<Onboarding step={onboarding} setStep={setOnboarding} later={()=>setOnboarding(3)}/>} 
  {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
  <Header tab={tab} name={profile.name} settings={()=>setSettings('menu')}/>
  <div className="content">
   {tab==='Today'&&<Today checkin={checkin} mood={moodText} profile={profile} done={done} go={go} open={setDetail}/>} 
   {tab==='Check'&&<CheckScreen value={checkin} setValue={setCheckin} save={()=>{flash('今日の状態を記録しました');setTimeout(()=>go('Today'),550)}}/>}
   {tab==='AI'&&<AIScreen chats={chats} text={chatText} setText={setChatText} send={sendChat}/>} 
   {tab==='Discover'&&<DiscoverScreen category={category} setCategory={setCategory} items={filtered} open={setDetail}/>} 
   {tab==='Circle'&&<CircleScreen circles={circleSeed} joined={joined} toggle={id=>setJoined(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])} open={setCircle}/>} 
   {tab==='Place'&&<PlaceScreen category={placeCat} setCategory={setPlaceCat} open={setPlace}/>} 
  </div>
  <nav className="tabbar" aria-label="メインナビゲーション">{NAV.map(({label,icon:Icon})=><button key={label} className={tab===label?'active':''} onClick={()=>go(label)}><Icon size={19}/><span>{label}</span></button>)}</nav>
  {detail&&<Modal onClose={()=>setDetail(null)}><img className="modal-image" src={detail.image} alt=""/><p className="chipline"><span>{detail.category}</span> <Clock size={13}/> {detail.minutes}</p><h2>{detail.title}</h2><p>{detail.description}</p><div className="reason"><Sparkles size={18}/><div><strong>今日のおすすめ理由</strong><p>{detail.reason}</p></div></div><div className="modal-actions"><button className="primary" onClick={()=>{setDone(v=>v.includes(detail.title)?v:[...v,detail.title]);flash('今日やったことに追加しました');setDetail(null)}}>やってみる</button><button onClick={()=>{flash('あとで見るに保存しました');setDetail(null)}}>あとで</button><button className="text-button" onClick={()=>setDetail(null)}>興味なし</button></div></Modal>}
  {circle&&<CircleDetail id={circle} posts={posts} setPosts={setPosts} text={postText} setText={setPostText} likes={likes} setLikes={setLikes} close={()=>setCircle(null)}/>} 
  {place&&<PlaceDetail place={place} close={()=>setPlace(null)}/>} 
  {settings&&<SettingsModal page={settings} setPage={setSettings} profile={profile} setProfile={setProfile} save={()=>{flash('プロフィールを保存しました');setSettings(null)}}/>}
 </section></main>
}

function Header({tab,name,settings}:{tab:Tab;name:string;settings:()=>void}){const titles:Record<Tab,string>={Today:`こんばんは、${name}さん 🌙`,Check:'今日のチェックイン',AI:'AI Camellia',Discover:'今日のおすすめ',Circle:'Circle',Place:'渋谷エリア'};return <header className="topbar"><div><p className="eyebrow">{tab==='Today'?'9月3日・木曜日':tab==='Check'?'毎日10秒チェック':tab==='AI'?'YOUR WELLBEING PARTNER':'CAMELLIA'}</p><h1>{titles[tab]}</h1></div><div className="top-actions"><button aria-label="通知"><Bell size={18}/></button><button onClick={settings} aria-label="設定"><Settings size={18}/></button></div></header>}

function Today({checkin,mood,profile,done,go,open}:{checkin:Checkin;mood:string;profile:Profile;done:string[];go:(t:Tab)=>void;open:(d:DiscoverItem)=>void}){return <>
 <section className="hero-card"><div className="hero-row"><div><p className="eyebrow">今日のあなた</p><h2>{checkin.condition==='良い'?'穏やかに過ごせそう':checkin.condition==='悪い'?'今日は休むことを一番に':'少し疲れているみたい'}</h2></div><div className="camellia">✿</div></div>
  <StatusRow label="身体" value={checkin.condition} score={checkin.condition==='良い'?5:checkin.condition==='普通'?4:checkin.condition==='疲れ気味'?3:2}/><StatusRow label="心" value={mood} score={checkin.mood}/><StatusRow label="睡眠" value={`${Math.floor(checkin.sleep)}時間${Math.round(checkin.sleep%1*60)||''}${checkin.sleep%1?'分':''}`} score={Math.min(5,Math.round(checkin.sleep/1.5))} blue/>
  {profile.periodEnabled&&<div className="period"><span>生理予定まで</span><strong>{checkin.period==='記録しない'?'記録なし':checkin.period}</strong></div>}<p className="gentle-note">{checkin.sleep<7?'睡眠が少し短めです。今日は頑張りすぎず、短い休憩を自分への贈りものに。':'よく休めています。心地よいペースで今日を楽しみましょう。'}</p><button className="subtle-link" onClick={()=>go('Check')}>今日の状態を見直す <ChevronRight size={15}/></button></section>
 <section className="section-block"><p className="eyebrow">MAKE A MOMENT</p><h2 className="serif-title">今日は、自分のために何する？</h2><div className="action-grid">{actions.map(({label,icon:Icon,tint})=><button key={label} className={`action ${tint}`} onClick={()=>go('Discover')}><Icon size={21}/><span>{label}</span></button>)}</div></section>
 <section className="section-block recommendations"><div className="section-title"><h2>今日のおすすめ</h2><button onClick={()=>go('Discover')}>すべて見る <ChevronRight size={15}/></button></div>{discover.slice(0,2).map(item=><ItemCard key={item.id} item={item} open={()=>open(item)}/>)}</section>
 {done.length>0&&<section className="section-block done-block"><p className="eyebrow">TODAY'S MOMENTS</p><h2 className="serif-title">今日、自分のためにしたこと</h2>{done.map(x=><div className="done-item" key={x}><Check size={15}/>{x}</div>)}</section>}
 </>}
function StatusRow({label,value,score,blue}:{label:string;value:string;score:number;blue?:boolean}){return <div className="meter-row"><span>{label}</span><div className={`dots ${blue?'blue':label==='心'?'purple':''}`}>{[1,2,3,4,5].map(x=><i key={x} className={x>score?'empty':''}/>)}</div><b>{value}</b></div>}

function CheckScreen({value,setValue,save}:{value:Checkin;setValue:(v:Checkin)=>void;save:()=>void}){const history=[3,4,2,3,4,3,value.mood];return <><section className="intro"><div className="flower-small">✿</div><h2>今日はどう？</h2><p>全部答えなくても大丈夫。今の自分を少しだけ見つめてみましょう。</p></section><section className="form-card"><label>気分</label><div className="moods">{['😣','😕','😌','🙂','☺️'].map((x,i)=><button key={x} className={value.mood===i+1?'selected':''} onClick={()=>setValue({...value,mood:i+1})}><span>{x}</span><small>{['つらい','少しつらい','普通','良い','とても良い'][i]}</small></button>)}</div><label>睡眠時間 <strong>{Math.floor(value.sleep)}時間{Math.round(value.sleep%1*60)||''}{value.sleep%1?'分':''}</strong></label><input type="range" min="3" max="10" step="0.25" value={value.sleep} onChange={e=>setValue({...value,sleep:+e.target.value})}/><Segment label="体調" options={['良い','普通','疲れ気味','悪い']} value={value.condition} set={condition=>setValue({...value,condition})}/><Segment label="ストレス" options={['低い','普通','やや高い','高い']} value={value.stress} set={stress=>setValue({...value,stress})}/><Segment label="生理" options={['生理中','予定まで6日','記録しない']} value={value.period} set={period=>setValue({...value,period})}/><button className="primary wide" onClick={save}>今日の状態を保存</button></section><section className="history-card"><div><p className="eyebrow">PAST 7 DAYS</p><h2>7日間のやさしい振り返り</h2></div><div className="chart">{history.map((x,i)=><div key={i}><i style={{height:`${22+x*10}px`}}/><small>{['金','土','日','月','火','水','今日'][i]}</small></div>)}</div><p>良い日も、そうでない日も、どちらもあなたの大切な一日です。</p></section></>}
function Segment({label,options,value,set}:{label:string;options:string[];value:string;set:(x:string)=>void}){return <div className="field"><label>{label}</label><div className="segments">{options.map(x=><button key={x} className={value===x?'selected':''} onClick={()=>set(x)}>{x}</button>)}</div></div>}

function AIScreen({chats,text,setText,send}:{chats:Chat[];text:string;setText:(x:string)=>void;send:(x?:string)=>void}){return <div className="chat-screen"><section className="ai-context"><div className="flower-small">✿</div><div><strong>今日のあなたをふまえて</strong><p>睡眠 {`6時間前後`}・少し疲れ気味</p></div></section><div className="messages">{chats.map((m,i)=><div key={i} className={`message ${m.from}`}>{m.text.split('\n').map((l,j)=><span key={j}>{l}</span>)}</div>)}</div><div className="quick"><p>こんなことを話せます</p>{['疲れた','眠れない','何かしたい','美容','仕事','誰かと話したい'].map(x=><button key={x} onClick={()=>send(x)}>{x}</button>)}</div><form className="chat-input" onSubmit={(e:FormEvent)=>{e.preventDefault();send()}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="今の気持ちを話してね…" aria-label="AIへのメッセージ"/><button aria-label="送信"><Send size={18}/></button></form></div>}
function reply(q:string,c:Checkin){if(/疲|仕事/.test(q))return `この数日、睡眠時間が${c.sleep<7?'少し短くなっています':'取れています'}。今日は無理に頑張るより、5分だけ休む時間を作ってもよさそうです。`;if(/イライラ|話/.test(q))return 'そう感じているんですね。まずはその気持ちを否定しなくて大丈夫。よければ、何があったかもう少し聞かせてください。';if(/眠/.test(q))return '眠れない夜は、眠ろうと頑張りすぎなくて大丈夫。照明を落として、ゆっくり4回だけ呼吸してみませんか？';if(/美容/.test(q))return '今日は肌も気持ちも休ませる、シンプルな保湿ケアがおすすめ。近くのヘッドスパも見てみますか？';if(/運動|何か|暇/.test(q))return '気分転換なら、15分の散歩か5分ストレッチはどうでしょう。できなくても問題ありません。';if(/食/.test(q))return '疲れ気味の日は、鉄分とたんぱく質を少し意識。卵や豆を使う簡単な一皿をおすすめします。';if(/学/.test(q))return '10分だけ気になることを調べて、3行メモする小さな学びはいかがでしょう。';return '話してくれてありがとう。今のあなたに一番近いのは「休みたい」「気分転換したい」「誰かに聞いてほしい」のどれですか？'}

function DiscoverScreen({category,setCategory,items,open}:{category:string;setCategory:(x:string)=>void;items:DiscoverItem[];open:(x:DiscoverItem)=>void}){return <><section className="intro compact"><h2>今日の私に、ちょうどいいこと</h2><p>小さな選択から、心地よい一日を。</p></section><div className="filter-scroll">{['すべて','整える','楽しむ','学ぶ','美容','運動','食事','休む'].map(x=><button className={category===x?'selected':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><section className="discovery-list">{items.map(item=><ItemCard item={item} key={item.id} open={()=>open(item)}/>)}</section></>}
function ItemCard({item,open}:{item:DiscoverItem;open:()=>void}){return <button className="recommend-card" onClick={open}><img src={item.image} alt=""/><div><small>{item.category} ・ {item.minutes}</small><strong>{item.title}</strong><span>{item.description}</span></div><ChevronRight size={18}/></button>}

function CircleScreen({circles,joined,toggle,open}:{circles:typeof circleSeed;joined:number[];toggle:(id:number)=>void;open:(id:number)=>void}){return <><div className="searchbar"><Search size={16}/><input placeholder="Circleを検索"/></div><section className="intro compact"><h2>同じ気持ちの誰かと、ゆるくつながる</h2><p>比べなくていい、小さな目的別コミュニティ。</p></section><div className="circle-list">{circles.map(c=><article className="circle-card" key={c.id} onClick={()=>open(c.id)}><div className="circle-icon">{c.icon}</div><div><h3>{c.name}</h3><small>{c.members}</small><p>{c.desc}</p></div><button className={joined.includes(c.id)?'joined':''} onClick={e=>{e.stopPropagation();toggle(c.id)}}>{joined.includes(c.id)?'参加中':'参加'}</button></article>)}</div></>}
function CircleDetail({id,posts,setPosts,text,setText,likes,setLikes,close}:{id:number;posts:string[];setPosts:(x:string[])=>void;text:string;setText:(x:string)=>void;likes:number[];setLikes:(x:number[])=>void;close:()=>void}){const c=circleSeed.find(x=>x.id===id)!;return <div className="full-panel"><header><button onClick={close}><ChevronLeft/></button><div><h2>{c.name}</h2><small>{c.members}</small></div></header><div className="panel-body"><div className="circle-welcome"><span>{c.icon}</span><p>{c.desc}<br/>気軽に今日のことをシェアしましょう。</p></div><form className="post-compose" onSubmit={e=>{e.preventDefault();if(text.trim()){setPosts([text.trim(),...posts]);setText('')}}}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="今、シェアしたいことは？"/><button className="primary">投稿する</button></form>{posts.map((p,i)=><article className="post" key={`${p}-${i}`}><div className="avatar">{['さ','み','あ','ゆ'][i%4]}</div><div><strong>{['さくら','miki','あや','yumi'][i%4]}</strong><small> ・ {i+1}時間前</small><p>{p}</p><button className={likes.includes(i)?'liked':''} onClick={()=>setLikes(likes.includes(i)?likes.filter(x=>x!==i):[...likes,i])}><Heart size={16}/> {12+i+(likes.includes(i)?1:0)}</button></div></article>)}</div></div>}

function PlaceScreen({category,setCategory,open}:{category:string;setCategory:(x:string)=>void;open:(x:typeof places[number])=>void}){const shown=category==='すべて'?places:places.filter(x=>x.cat===category);return <><section className="map-card"><div className="map-lines"/><MapPin size={30}/><div><strong>渋谷エリア</strong><span>現在地はプロトタイプ表示です</span></div></section><div className="filter-scroll">{['すべて','美容','リラックス','運動','カフェ','温泉','イベント'].map(x=><button className={category===x?'selected':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><section className="place-list"><h2>おすすめの場所</h2>{shown.map(p=><button className="place-card" key={p.id} onClick={()=>open(p)}><img src={p.image} alt=""/><div><small>{p.sub}</small><strong>{p.name}</strong><span>{p.walk} ・ <Star size={12}/> {p.rating}</span><b>{p.price}</b></div><ChevronRight size={18}/></button>)}</section></>}
function PlaceDetail({place,close}:{place:typeof places[number];close:()=>void}){return <Modal onClose={close}><img className="modal-image" src={place.image} alt=""/><p className="chipline"><span>{place.sub}</span> {place.walk}</p><h2>{place.name}</h2><p>慌ただしい日常から少し離れ、自分の呼吸に戻れる落ち着いた空間です。</p><div className="info-grid"><div><small>営業時間</small><strong>{place.hours}</strong></div><div><small>料金目安</small><strong>{place.price}</strong></div></div><div className="fake-map"><div className="map-lines"/><MapPin/></div><a className="primary wide link" href="#" onClick={e=>{e.preventDefault();alert('予約サイトはデモ表示です')}}>予約サイトへ</a></Modal>}

function SettingsModal({page,setPage,profile,setProfile,save}:{page:'menu'|'profile'|'pricing';setPage:(x:'menu'|'profile'|'pricing'|null)=>void;profile:Profile;setProfile:(p:Profile)=>void;save:()=>void}){return <Modal onClose={()=>setPage(null)}>{page==='menu'?<><p className="eyebrow">SETTINGS</p><h2>Camellia 設定</h2><button className="settings-row" onClick={()=>setPage('profile')}><UserRound/>プロフィール <ChevronRight/></button><button className="settings-row" onClick={()=>setPage('pricing')}><Sparkles/>料金プラン <ChevronRight/></button><p className="settings-note">記録はこの端末内にのみ保存されます。</p></>:page==='profile'?<ProfileForm value={profile} setValue={setProfile} save={save} back={()=>setPage('menu')}/>:<Pricing back={()=>setPage('menu')}/>}</Modal>}
function ProfileForm({value,setValue,save,back}:{value:Profile;setValue:(x:Profile)=>void;save:()=>void;back:()=>void}){const interests=['美容','健康','運動','食事','メンタル','仕事','学び','推し活','趣味'];return <><button className="back-link" onClick={back}><ChevronLeft/>設定</button><h2>プロフィール</h2><div className="profile-form"><label>名前<input value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></label><label>年代<select value={value.age} onChange={e=>setValue({...value,age:e.target.value})}><option>20代</option><option>30代</option><option>40代</option><option>50代以上</option></select></label><label>ライフスタイル<input value={value.lifestyle} onChange={e=>setValue({...value,lifestyle:e.target.value})}/></label><label>今日大切にしたいこと<input value={value.priority} onChange={e=>setValue({...value,priority:e.target.value})}/></label><div><label>興味</label><div className="interest-grid">{interests.map(x=><button className={value.interests.includes(x)?'selected':''} key={x} onClick={()=>setValue({...value,interests:value.interests.includes(x)?value.interests.filter(y=>y!==x):[...value.interests,x]})}>{x}</button>)}</div></div><label className="switch-row">生理記録を使う<input type="checkbox" checked={value.periodEnabled} onChange={e=>setValue({...value,periodEnabled:e.target.checked})}/></label><button className="primary wide" onClick={save}>保存する</button></div></>}
function Pricing({back}:{back:()=>void}){return <><button className="back-link" onClick={back}><ChevronLeft/>設定</button><p className="eyebrow">PLAN</p><h2>あなたに合うCamelliaを</h2><div className="plans"><div><small>Camellia Free</small><h3>¥0 <span>/ 月</span></h3><p>Today・Check<br/>Circle参加<br/>Discover一部<br/>AI基本利用</p></div><div className="featured"><b>人気プラン</b><small>Camellia+</small><h3>¥680 <span>/ 月</span></h3><p>AI長期記憶・詳細な振り返り<br/>自分レポート<br/>高度なパーソナライズ<br/>限定Circle・提携特典</p></div><div><small>REAL</small><h3>体験ごと</h3><p>ヨガ・ピラティス・美容<br/>リラク・ワークショップ<br/>温泉・サウナ・イベント</p></div></div></>}

function Onboarding({step,setStep,later}:{step:number;setStep:(x:number)=>void;later:()=>void}){const pages=[{k:'今日、自分のために何する？',p:'あなたの毎日をやさしく整え、自分らしい人生を応援するパートナー。'},{k:'身体も、心も、美容も、仕事も。',p:'全部あなたの毎日の一部。どれも同じように大切に。'},{k:'今日のあなたに合った選択を',p:'Camelliaが一緒に探します。小さなことから、心地よく。'}];const x=pages[step];return <div className="onboarding"><div className="brand">Camellia <span>✿</span></div><div className="onboard-art"><div>✿</div><span>あなたのペースで</span></div><p className="eyebrow">WELCOME TO CAMELLIA</p><h1>{x.k}</h1><p>{x.p}</p><div className="pager">{pages.map((_,i)=><i className={i===step?'active':''} key={i}/>)}</div><button className="primary wide" onClick={()=>setStep(step+1)}>{step===2?'はじめる':'次へ'}</button><button className="text-button" onClick={later}>後で設定</button></div>}
