/* oxlint-disable react-compiler -- localStorage hydration and state transitions are intentionally centralized in this prototype store */
'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { captureContext } from '@/lib/memory/engine';
import { sessionAttribution } from '@/lib/analytics/attribution';
import { forwardEvent } from '@/lib/analytics/posthog';
import type { ActionDefinition,AnalyticsEventName,CamelliaState,Checkin,ConversationIntent,ConversationTopic,DailyFortune,DismissReason,FeedbackRating,Insight,InsightFeedback,Mood,Profile,SaveTiming,TreeLeaf } from '@/types';
export const STORAGE_KEY='camellia-prototype-v3'; const V2_KEY='camellia-prototype-v2'; const V1_KEY='camellia-prototype-v1';
const stamp=()=>new Date().toISOString(); const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
export function emptyState():CamelliaState{const now=stamp();return{version:3,profile:{id:uid(),name:'',age:'',interests:[],lifestyle:'',priority:'',periodEnabled:false,createdAt:now,updatedAt:now},checkins:[],actions:[],actionFeedback:[],savedActions:[],aiConversations:[],contextualMemory:[],insights:[],insightFeedback:[],fortunes:[],treeLeaves:[],analyticsEvents:[],onboardingComplete:false,createdAt:now,updatedAt:now}}
function migrate(raw:unknown):CamelliaState{const base=emptyState();if(!raw||typeof raw!=='object')return base;const old=raw as Partial<CamelliaState>&{version?:number};if(old.profile)base.profile={...base.profile,...old.profile};base.checkins=old.checkins??[];base.actions=old.actions??[];base.actionFeedback=old.actionFeedback??[];base.savedActions=(old.savedActions??[]).map(s=>({...s,timing:s.timing??'save_only'}));base.aiConversations=old.aiConversations??[];base.onboardingComplete=Boolean(old.onboardingComplete);return base}
function load():CamelliaState{if(typeof window==='undefined')return emptyState();try{const v3=localStorage.getItem(STORAGE_KEY);if(v3){const saved=JSON.parse(v3);return{...emptyState(),...saved,fortunes:saved.fortunes??[],treeLeaves:saved.treeLeaves??[],analyticsEvents:saved.analyticsEvents??[]}}const v2=localStorage.getItem(V2_KEY);if(v2)return migrate(JSON.parse(v2));const v1=localStorage.getItem(V1_KEY);if(v1)return migrate(JSON.parse(v1))}catch{}return emptyState()}
export function useCamelliaStore(){const[state,setState]=useState<CamelliaState>(()=>emptyState());const[ready,setReady]=useState(false);useEffect(()=>{setState(load());setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem(STORAGE_KEY,JSON.stringify({...state,updatedAt:stamp()}))},[state,ready]);
 const forwarded = useRef(new Set<string>());
 useEffect(()=>{if(!ready)return;const pending=state.analyticsEvents.filter(e=>!e.forwardedAt&&!forwarded.current.has(e.id));if(!pending.length)return;const sent=pending.filter(e=>{if(!forwardEvent(e,state))return false;forwarded.current.add(e.id);return true}).map(e=>e.id);if(sent.length)setState(s=>({...s,analyticsEvents:s.analyticsEvents.map(e=>sent.includes(e.id)?{...e,forwardedAt:stamp()}:e)}))},[ready,state]);
 const track=useCallback((name:AnalyticsEventName,properties?:Record<string,string|number|boolean>)=>setState(s=>({...s,analyticsEvents:[...s.analyticsEvents,{id:uid(),name,properties:{...properties,...sessionAttribution()},createdAt:stamp()}]})),[]);
 useEffect(()=>{if(ready&&sessionStorage.getItem('camellia-session')!=='1'){sessionStorage.setItem('camellia-session','1');track('session_start')}},[ready,track]);
 const viewCheck=useCallback(()=>track('check_view'),[track]);
 const startCheck=useCallback(()=>setState(s=>{const last=[...s.analyticsEvents].reverse().find(e=>e.name==='check_start'||e.name==='check_complete');if(last?.name==='check_start')return s;return{...s,analyticsEvents:[...s.analyticsEvents,{id:uid(),name:'check_start',properties:sessionAttribution(),createdAt:stamp()}]}}),[]);
 const memory=(s:CamelliaState,actionId:string,event:'proposed'|'saved'|'dismissed'|'started'|'completed'|'feedback',extra:Record<string,unknown>={})=>({id:uid(),actionId,event,context:captureContext(s),createdAt:stamp(),...extra});
 const updateProfile=useCallback((p:Partial<Profile>)=>setState(s=>({...s,profile:{...s.profile,...p,updatedAt:stamp()}})),[]);const completeOnboarding=useCallback(()=>setState(s=>({...s,onboardingComplete:true})),[]);
 const addCheckin=useCallback((v:{mood:Mood}&Partial<Omit<Checkin,'id'|'mood'|'createdAt'|'updatedAt'>>)=>{const now=stamp();setState(s=>({...s,checkins:[...s.checkins,{id:uid(),...v,createdAt:now,updatedAt:now}],analyticsEvents:[...s.analyticsEvents,{id:uid(),name:'check_complete',properties:{...sessionAttribution(),hasDetails:Boolean(v.sleep!==undefined||v.body||v.stress||v.periodDays!==undefined)},createdAt:now}]}))},[]);
 const recordProposals=useCallback((ids:string[])=>setState(s=>{const today=new Date().toDateString();const add=ids.filter(id=>!s.contextualMemory.some(m=>m.actionId===id&&m.event==='proposed'&&new Date(m.createdAt).toDateString()===today)).map(id=>memory(s,id,'proposed'));return add.length?{...s,contextualMemory:[...s.contextualMemory,...add]}:s}),[]);
 const startAction=useCallback((a:ActionDefinition)=>{const now=stamp();setState(s=>({...s,actions:[...s.actions,{id:uid(),actionId:a.id,title:a.title,category:a.category,status:'started',startedAt:now,createdAt:now,updatedAt:now}],contextualMemory:[...s.contextualMemory,memory(s,a.id,'started')]}))},[]);
 const completeAction=useCallback((id:string)=>setState(s=>{const a=s.actions.find(x=>x.id===id);return{...s,actions:s.actions.map(x=>x.id===id?{...x,status:'completed',completedAt:stamp(),updatedAt:stamp()}:x),contextualMemory:a?[...s.contextualMemory,memory(s,a.actionId,'completed')]:s.contextualMemory}}),[]);
 const skipAction=useCallback((a:ActionDefinition,reason:DismissReason)=>{const now=stamp();setState(s=>({...s,actions:[...s.actions,{id:uid(),actionId:a.id,title:a.title,category:a.category,status:'skipped',dismissReason:reason,createdAt:now,updatedAt:now}],contextualMemory:[...s.contextualMemory,memory(s,a.id,'dismissed',{dismissReason:reason})]}))},[]);
 const saveAction=useCallback((a:ActionDefinition,timing:SaveTiming)=>setState(s=>{const now=stamp();return{...s,savedActions:[...s.savedActions,{id:uid(),actionId:a.id,timing,createdAt:now,updatedAt:now}],contextualMemory:[...s.contextualMemory,memory(s,a.id,'saved',{saveTiming:timing})]}}),[]);
 const addFeedback=useCallback((recordId:string,actionId:string,rating:FeedbackRating)=>{const now=stamp();setState(s=>({...s,actionFeedback:[...s.actionFeedback,{id:uid(),actionRecordId:recordId,actionId,rating,createdAt:now,updatedAt:now}],contextualMemory:[...s.contextualMemory,memory(s,actionId,'feedback',{feedback:rating})]}))},[]);
 const addConversation=useCallback((u:string,a:string,intent:ConversationIntent,topics:ConversationTopic[])=>{const now=stamp();setState(s=>{const current=s.aiConversations[0]??{id:uid(),messages:[],createdAt:now,updatedAt:now};return{...s,aiConversations:[{...current,messages:[...current.messages,{id:uid(),role:'user',text:u,intent,topics,createdAt:now},{id:uid(),role:'assistant',text:a,intent,topics,createdAt:now}],updatedAt:now},...s.aiConversations.slice(1)]}})},[]);
 const syncInsights=useCallback((items:Insight[])=>setState(s=>({...s,insights:items})),[]);const feedbackInsight=useCallback((key:string,verdict:InsightFeedback['verdict'])=>{const now=stamp();setState(s=>({...s,insightFeedback:[...s.insightFeedback,{id:uid(),insightKey:key,verdict,createdAt:now,updatedAt:now}],insights:s.insights.map(i=>i.key===key?{...i,confidence:verdict==='incorrect'?Math.max(0,i.confidence-.5):Math.min(1,i.confidence+.15),updatedAt:now}:i)}))},[]);
 const setFortune=useCallback((fortune:DailyFortune)=>setState(s=>({...s,fortunes:[...s.fortunes.filter(f=>f.date!==fortune.date),fortune]})),[]);
 const addTreeLeaf=useCallback((leaf:Omit<TreeLeaf,'id'|'createdAt'|'updatedAt'|'reflections'|'status'>)=>{const now=stamp();setState(s=>({...s,treeLeaves:[...s.treeLeaves,{...leaf,id:uid(),status:'active',reflections:[],createdAt:now,updatedAt:now}],analyticsEvents:[...s.analyticsEvents,{id:uid(),name:'tree_add_complete',properties:{category:leaf.category,tagCount:leaf.meaningTags.length},createdAt:now}]}))},[]);
 const updateTreeLeaf=useCallback((id:string,patch:Partial<TreeLeaf>)=>setState(s=>({...s,treeLeaves:s.treeLeaves.map(l=>l.id===id?{...l,...patch,updatedAt:stamp()}:l)})),[]);
 const addTreeReflection=useCallback((id:string,text:string)=>{const now=stamp();setState(s=>({...s,treeLeaves:s.treeLeaves.map(l=>l.id===id?{...l,reflections:[...l.reflections,{id:uid(),text,createdAt:now,updatedAt:now}],updatedAt:now}:l),analyticsEvents:[...s.analyticsEvents,{id:uid(),name:'tree_reflection_add',createdAt:now}]}))},[]);
 const reset=useCallback(()=>{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(V2_KEY);localStorage.removeItem(V1_KEY);setState(emptyState())},[]);return{state,ready,updateProfile,completeOnboarding,addCheckin,recordProposals,startAction,completeAction,skipAction,saveAction,addFeedback,addConversation,syncInsights,feedbackInsight,setFortune,addTreeLeaf,updateTreeLeaf,addTreeReflection,viewCheck,startCheck,track,reset}}
