/* oxlint-disable react-compiler -- localStorage hydration and state transitions are intentionally centralized in this prototype store */
'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { captureContext } from '@/lib/memory/engine';
import { sessionAttribution } from '@/lib/analytics/attribution';
import { forwardEvent } from '@/lib/analytics/posthog';
import { deleteSyncedCamelliaData, prepareSchoolParkAccount, syncToSchoolPark } from '@/lib/schoolpark/sync';
import { resetAnalyticsIdentity } from '@/lib/analytics/posthog';
import type { ActionDefinition,AnalyticsEventName,CamelliaState,Checkin,ConversationIntent,ConversationTopic,DailyFortune,DismissReason,FeedbackRating,Insight,InsightFeedback,Mood,Profile,SaveTiming,TreeLeaf } from '@/types';
export const STORAGE_KEY='camellia-prototype-v3'; const V2_KEY='camellia-prototype-v2'; const V1_KEY='camellia-prototype-v1';
const stamp=()=>new Date().toISOString(); const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
export function emptyState():CamelliaState{const now=stamp();return{version:3,profile:{id:uid(),name:'',age:'',interests:[],lifestyle:'',priority:'',periodEnabled:false,createdAt:now,updatedAt:now},checkins:[],actions:[],actionFeedback:[],savedActions:[],aiConversations:[],contextualMemory:[],personalMemories:[],insights:[],insightFeedback:[],fortunes:[],treeLeaves:[],analyticsEvents:[],onboardingComplete:false,createdAt:now,updatedAt:now}}
export function migrate(raw:unknown):CamelliaState{const base=emptyState();if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('LOCAL_DATA_UNREADABLE');const old=raw as Partial<CamelliaState>&{version?:number};if(old.profile)base.profile={...base.profile,...old.profile};base.checkins=old.checkins??[];base.actions=old.actions??[];base.actionFeedback=old.actionFeedback??[];base.savedActions=(old.savedActions??[]).map(s=>({...s,timing:s.timing??'save_only'}));base.aiConversations=old.aiConversations??[];base.contextualMemory=old.contextualMemory??[];base.personalMemories=old.personalMemories??[];base.insights=old.insights??[];base.insightFeedback=old.insightFeedback??[];base.fortunes=old.fortunes??[];base.treeLeaves=old.treeLeaves??[];base.analyticsEvents=old.analyticsEvents??[];base.onboardingComplete=Boolean(old.onboardingComplete);base.createdAt=old.createdAt??base.createdAt;base.updatedAt=old.updatedAt??base.updatedAt;return base}
export function load():CamelliaState{if(typeof window==='undefined')return emptyState();try{const v3=localStorage.getItem(STORAGE_KEY);if(v3){const saved=JSON.parse(v3);if(!saved||saved.version!==3||!saved.profile||typeof saved.profile.name!=='string'||!Array.isArray(saved.profile.interests)||['checkins','actions','actionFeedback','savedActions','aiConversations','contextualMemory','insights','insightFeedback'].some(key=>!Array.isArray(saved[key])))throw new Error('LOCAL_DATA_UNREADABLE');return{...emptyState(),...saved,fortunes:saved.fortunes??[],treeLeaves:saved.treeLeaves??[],analyticsEvents:saved.analyticsEvents??[]}}const v2=localStorage.getItem(V2_KEY);if(v2)return migrate(JSON.parse(v2));const v1=localStorage.getItem(V1_KEY);if(v1)return migrate(JSON.parse(v1))}catch{throw new Error('LOCAL_DATA_UNREADABLE')}return emptyState()}
export function useCamelliaStore(){const[state,setState]=useState<CamelliaState>(()=>emptyState());const[ready,setReady]=useState(false);const[storageError,setStorageError]=useState('');const skipNextSync=useRef(false);const hydrated=useRef(false);useEffect(()=>{if(hydrated.current)return;hydrated.current=true;try{setState(load())}catch{setStorageError('LOCAL_DATA_UNREADABLE')}setReady(true)},[]);useEffect(()=>{if(!ready||storageError)return;localStorage.setItem(STORAGE_KEY,JSON.stringify({...state,updatedAt:stamp()}));if(skipNextSync.current){skipNextSync.current=false;return}syncToSchoolPark(state)},[state,ready,storageError]);
 const forwarded = useRef(new Set<string>());
 useEffect(()=>{if(!ready)return;const pending=state.analyticsEvents.filter(e=>!e.forwardedAt&&!forwarded.current.has(e.id));if(!pending.length)return;const sent=pending.filter(e=>{if(!forwardEvent(e,state))return false;forwarded.current.add(e.id);return true}).map(e=>e.id);if(sent.length)setState(s=>({...s,analyticsEvents:s.analyticsEvents.map(e=>sent.includes(e.id)?{...e,forwardedAt:stamp()}:e)}))},[ready,state]);
 const track=useCallback((name:AnalyticsEventName,properties?:Record<string,string|number|boolean>)=>setState(s=>({...s,analyticsEvents:[...s.analyticsEvents,{id:uid(),name,properties:{...properties,...sessionAttribution()},createdAt:stamp()}]})),[]);
 useEffect(()=>{if(ready&&sessionStorage.getItem('camellia-session')!=='1'){sessionStorage.setItem('camellia-session','1');track('session_start')}},[ready,track]);
 const viewCheck=useCallback(()=>track('check_view'),[track]);
 const startCheck=useCallback(()=>setState(s=>{const last=[...s.analyticsEvents].reverse().find(e=>e.name==='check_start'||e.name==='check_complete');if(last?.name==='check_start')return s;return{...s,analyticsEvents:[...s.analyticsEvents,{id:uid(),name:'check_start',properties:sessionAttribution(),createdAt:stamp()}]}}),[]);
 const memory=(s:CamelliaState,actionId:string,event:'proposed'|'saved'|'dismissed'|'started'|'completed'|'feedback',extra:Record<string,unknown>={})=>({id:uid(),actionId,event,context:captureContext(s),createdAt:stamp(),...extra});
 const updateProfile=useCallback((p:Partial<Profile>)=>setState(s=>({...s,profile:{...s.profile,...p,updatedAt:stamp()}})),[]);const completeOnboarding=useCallback(()=>setState(s=>({...s,onboardingComplete:true})),[]);
 const addCheckin=useCallback((v:{mood:Mood}&Partial<Omit<Checkin,'id'|'mood'|'createdAt'|'updatedAt'>>)=>{const now=stamp();setState(s=>({...s,checkins:[...s.checkins,{id:uid(),...v,createdAt:now,updatedAt:now}],analyticsEvents:[...s.analyticsEvents,{id:uid(),name:'check_complete',properties:{...sessionAttribution(),hasDetails:Boolean(v.sleep!==undefined||v.body||v.stress||v.periodDays!==undefined)},createdAt:now}]}))},[]);
 const recordProposals=useCallback((ids:string[])=>setState(s=>{const today=new Date().toDateString();const add=ids.filter(id=>!s.contextualMemory.some(m=>m.actionId===id&&m.event==='proposed'&&new Date(m.createdAt).toDateString()===today)).map(id=>memory(s,id,'proposed'));return add.length?{...s,contextualMemory:[...s.contextualMemory,...add]}:s}),[]);
 const startAction=useCallback((a:ActionDefinition)=>{const now=stamp();setState(s=>({...s,actions:[...s.actions,{id:uid(),actionId:a.id,title:a.title,category:a.category,status:'started',startedAt:now,createdAt:now,updatedAt:now}],contextualMemory:[...s.contextualMemory,memory(s,a.id,'started')]}))},[]);
 const completeAction=useCallback((id:string)=>setState(s=>{const a=s.actions.find(x=>x.id===id);return{...s,actions:s.actions.map(x=>x.id===id?{...x,status:'completed',completedAt:stamp(),updatedAt:stamp()}:x),contextualMemory:a?[...s.contextualMemory,memory(s,a.actionId,'completed')]:s.contextualMemory}}),[]);
 const skipAction=useCallback((a:ActionDefinition,reason:DismissReason)=>{const now=stamp();setState(s=>({...s,actions:[...s.actions,{id:uid(),actionId:a.id,title:a.title,category:a.category,status:'skipped',dismissReason:reason,createdAt:now,updatedAt:now}],contextualMemory:[...s.contextualMemory,memory(s,a.id,'dismissed',{dismissReason:reason})]}))},[]);
 const saveAction=useCallback((a:ActionDefinition,timing:SaveTiming)=>setState(s=>{const now=stamp();return{...s,savedActions:[...s.savedActions,{id:uid(),actionId:a.id,timing,createdAt:now,updatedAt:now}],contextualMemory:[...s.contextualMemory,memory(s,a.id,'saved',{saveTiming:timing})]}}),[]);
 const addFeedback=useCallback((recordId:string,actionId:string,rating:FeedbackRating)=>{const now=stamp();setState(s=>s.actionFeedback.some(f=>f.actionRecordId===recordId)?s:({...s,actionFeedback:[...s.actionFeedback,{id:uid(),actionRecordId:recordId,actionId,rating,createdAt:now,updatedAt:now}],contextualMemory:[...s.contextualMemory,memory(s,actionId,'feedback',{feedback:rating})]}))},[]);
 const addConversation=useCallback((u:string,a:string,intent:ConversationIntent,topics:ConversationTopic[])=>{const now=stamp();setState(s=>{const current=s.aiConversations[0]??{id:uid(),messages:[],createdAt:now,updatedAt:now};return{...s,aiConversations:[{...current,messages:[...current.messages,{id:uid(),role:'user',text:u,intent,topics,createdAt:now},{id:uid(),role:'assistant',text:a,intent,topics,createdAt:now}],updatedAt:now},...s.aiConversations.slice(1)]}})},[]);
 const syncInsights=useCallback((items:Insight[])=>setState(s=>({...s,insights:items})),[]);const feedbackInsight=useCallback((key:string,verdict:InsightFeedback['verdict'])=>{const now=stamp();setState(s=>({...s,insightFeedback:[...s.insightFeedback,{id:uid(),insightKey:key,verdict,createdAt:now,updatedAt:now}],insights:s.insights.map(i=>i.key===key?{...i,confidence:verdict==='incorrect'?Math.max(0,i.confidence-.5):Math.min(1,i.confidence+.15),updatedAt:now}:i)}))},[]);
 const setFortune=useCallback((fortune:DailyFortune)=>setState(s=>({...s,fortunes:[...s.fortunes.filter(f=>f.date!==fortune.date),fortune]})),[]);
 const addTreeLeaf=useCallback((leaf:Omit<TreeLeaf,'id'|'createdAt'|'updatedAt'|'reflections'|'status'>)=>{const now=stamp();setState(s=>({...s,treeLeaves:[...s.treeLeaves,{...leaf,id:uid(),status:'active',reflections:[],createdAt:now,updatedAt:now}],analyticsEvents:[...s.analyticsEvents,{id:uid(),name:'tree_add_complete',properties:{category:leaf.category,tagCount:leaf.meaningTags.length},createdAt:now}]}))},[]);
 const updateTreeLeaf=useCallback((id:string,patch:Partial<TreeLeaf>)=>setState(s=>({...s,treeLeaves:s.treeLeaves.map(l=>l.id===id?{...l,...patch,updatedAt:stamp()}:l)})),[]);
 const addTreeReflection=useCallback((id:string,text:string)=>{const now=stamp();setState(s=>({...s,treeLeaves:s.treeLeaves.map(l=>l.id===id?{...l,reflections:[...l.reflections,{id:uid(),text,createdAt:now,updatedAt:now}],updatedAt:now}:l),analyticsEvents:[...s.analyticsEvents,{id:uid(),name:'tree_reflection_add',createdAt:now}]}))},[]);
 const remember=useCallback((text:string)=>setState(s=>{const clean=text.trim().slice(0,500);if(!clean)return s;const now=stamp();return{...s,personalMemories:[...(s.personalMemories??[]),{id:uid(),text:clean,createdAt:now,updatedAt:now,source:'explicit_conversation' as const}]}}),[]);
 const forget=useCallback((id:string)=>setState(s=>({...s,personalMemories:(s.personalMemories??[]).map(item=>item.id===id?{...item,text:'',status:'removed' as const,updatedAt:stamp()}:item)})),[]);
 const prepareAccount=useCallback(async(accountUid:string,useRemote=false)=>{const restored=await prepareSchoolParkAccount(load(),accountUid,useRemote);setState(restored)},[]);
 const reset=useCallback(async()=>{const result=await deleteSyncedCamelliaData(()=>{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(V2_KEY);localStorage.removeItem(V1_KEY);localStorage.removeItem('camellia-sync-sent');localStorage.removeItem('camellia-sync-conflict');localStorage.removeItem('camellia-cache-owner');for(const key of Object.keys(localStorage))if(key.startsWith('camellia-sync-sent:')||key.startsWith('camellia-sync-conflict:')||key.startsWith('camellia-cloud-version:')||key.startsWith('camellia-local-backup:'))localStorage.removeItem(key);resetAnalyticsIdentity()});skipNextSync.current=true;setState(emptyState());return result},[]);return{state,ready,storageError,remember,forget,prepareAccount,updateProfile,completeOnboarding,addCheckin,recordProposals,startAction,completeAction,skipAction,saveAction,addFeedback,addConversation,syncInsights,feedbackInsight,setFortune,addTreeLeaf,updateTreeLeaf,addTreeReflection,viewCheck,startCheck,track,reset}}
