import { useState } from 'react';
import type { Profile } from '@/types';

export function OnboardingScreen({ onFinish }:{onFinish:(profile:Partial<Profile>)=>void}) {
  const [step,setStep]=useState(0); const [name,setName]=useState(''); const [age,setAge]=useState('30代'); const [interests,setInterests]=useState<string[]>([]); const [periodEnabled,setPeriod]=useState(false); const [lifestyle,setLifestyle]=useState('仕事中心'); const [availableMinutes,setAvailable]=useState(10);
  const slides=[['今日は、自分のために何する？','Camelliaは、今のあなたを知り、今日に合う小さな選択を一緒に見つけます。'],['毎日、全部記録しなくて大丈夫','気分をひとつ選ぶだけでも、今日の提案は少し変わります。'],['昨日より今日、少しあなたを理解する','行動と振り返りを重ねるほど、提案があなたらしく育ちます。']];
  if(step<3) return <main className="onboarding"><div className="flower-mark">✿</div><p className="eyebrow">Camellia</p><h1>{slides[step][0]}</h1><p>{slides[step][1]}</p><div className="dots">{slides.map((_,i)=><i key={i} className={i===step?'on':''}/>)}</div><button className="primary" onClick={()=>setStep(step+1)}>{step===2?'プロフィールを設定':'次へ'}</button></main>;
  const options=['美容','運動・健康','メンタルケア','音楽・趣味','学び'];
  return <main className="onboarding profile-setup"><p className="eyebrow">最後に、あなたのことを少し</p><h1>提案をあなたらしく</h1><label>呼び名（任意）<input value={name} onChange={e=>setName(e.target.value)} placeholder="例：さくら"/></label><label>年代<select value={age} onChange={e=>setAge(e.target.value)}><option>20代</option><option>30代</option><option>40代</option><option>50代以上</option></select></label><label>今の生活に近いもの<select value={lifestyle} onChange={e=>setLifestyle(e.target.value)}><option>仕事中心</option><option>仕事と育児</option><option>学業中心</option><option>家事・ケア中心</option><option>シフト勤務</option></select></label><label>今日使えそうな時間<select value={availableMinutes} onChange={e=>setAvailable(Number(e.target.value))}><option value="5">5分</option><option value="10">10分</option><option value="20">20分</option><option value="45">45分以上</option></select></label><fieldset><legend>興味（複数選択）</legend><div className="chips">{options.map(x=><button type="button" className={interests.includes(x)?'selected':''} key={x} onClick={()=>setInterests(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x])}>{x}</button>)}</div></fieldset><label className="toggle"><input type="checkbox" checked={periodEnabled} onChange={e=>setPeriod(e.target.checked)}/> 生理周期の情報を提案に使う</label><button className="primary" onClick={()=>onFinish({name,age,interests,periodEnabled,lifestyle,availableMinutes,priority:''})}>Todayをはじめる</button></main>;
}
