import { useEffect, useMemo, useRef, useState } from 'react';
import { MessageCircle, Sparkles } from 'lucide-react';
import { ActionCard } from '@/components/ActionCard';
import { buildTodaySummary, getTimeBand } from '@/lib/recommendation';
import type { CamelliaState, Checkin, FeedbackRating, Mood, Recommendation } from '@/types';

const moods:{value:Mood;emoji:string;label:string}[]=[{value:5,emoji:'😊',label:'とても良い'},{value:4,emoji:'🙂',label:'良い'},{value:3,emoji:'😐',label:'普通'},{value:2,emoji:'😔',label:'少しつらい'},{value:1,emoji:'😣',label:'つらい'}];
export function TodayScreen({state,recommendations,forceNight=false,onCheckView,onCheckStart,onCheckin,onOpenAction,onIntent,onTalk,onFortune,onTree,onComplete,onFeedback,onProposals}:{state:CamelliaState;recommendations:Recommendation[];forceNight?:boolean;onCheckView:()=>void;onCheckStart:()=>void;onCheckin:(v:{mood:Mood}&Partial<Omit<Checkin,'id'|'mood'|'createdAt'|'updatedAt'>>)=>void;onOpenAction:(r:Recommendation)=>void;onIntent:(x:string)=>void;onTalk:()=>void;onFortune:()=>void;onTree:()=>void;onComplete:(id:string)=>void;onFeedback:(recordId:string,actionId:string,rating:FeedbackRating)=>void;onProposals:(ids:string[])=>void}) {
  const checkViewSent=useRef(false);
  useEffect(()=>{const timer=window.setTimeout(()=>{if(!checkViewSent.current){checkViewSent.current=true;onCheckView()}},0);return()=>window.clearTimeout(timer)},[onCheckView]);
  const [mood,setMood]=useState<Mood|undefined>(); const [more,setMore]=useState(false); const [sleep,setSleep]=useState(''); const [body,setBody]=useState<Checkin['body']>(); const [stress,setStress]=useState<Checkin['stress']>(); const [period,setPeriod]=useState(''); const [saved,setSaved]=useState(false);
  const date=useMemo(()=>new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(new Date()),[]);
  const active=state.actions.filter(a=>a.status==='started');
  const reflection=state.actions.filter(a=>a.status==='completed'&&!state.actionFeedback.some(f=>f.actionRecordId===a.id));
  useEffect(()=>{if(state.checkins.length)onProposals(recommendations.map(r=>r.action.id))},[recommendations,state.checkins.length,onProposals]);
  const displayDate=useMemo(()=>{const value=new Date();if(forceNight)value.setHours(21,0,0,0);return value},[forceNight]);
  const timeBand=getTimeBand(displayDate); const greeting={朝:'おはよう',昼:'こんにちは',夕方:'今日もおつかれさま',夜:'こんばんは'}[timeBand];
  const save=()=>{if(!mood)return;onCheckin({mood,sleep:sleep?Number(sleep):undefined,body:body||undefined,stress:stress||undefined,periodDays:period?Number(period):undefined});setSaved(true);setMore(false)};
  return <main className="screen today"><header><div><p className="date">{date}</p><h1>{state.profile.name?`${state.profile.name}さん、${greeting}`:`${greeting}`}</h1></div><span className="logo-small">Camellia ✿</span></header>
    <section className="check-card"><h2>{state.checkins.length?'今日はどう？':'はじめまして。まず、今日のあなたを少しだけ教えてください。'}</h2><div className="moods">{moods.map(x=><button aria-label={x.label} className={mood===x.value?'selected':''} key={x.value} onClick={()=>{onCheckStart();setMood(x.value);setSaved(false)}}>{x.emoji}</button>)}</div><button className="text-button" onClick={()=>setMore(!more)}>{more?'閉じる':'＋ もう少し教える'}</button>{more&&<div className="more-check"><label>睡眠（時間）<input type="number" min="0" max="14" step="0.5" value={sleep} onChange={e=>setSleep(e.target.value)} placeholder="例 6.5"/></label><label>身体<select value={body??''} onChange={e=>setBody(e.target.value as Checkin['body'])}><option value="">選択しない</option><option>良い</option><option>普通</option><option>疲れ気味</option><option>悪い</option></select></label><label>ストレス<select value={stress??''} onChange={e=>setStress(e.target.value as Checkin['stress'])}><option value="">選択しない</option><option>低い</option><option>普通</option><option>やや高い</option><option>高い</option></select></label>{state.profile.periodEnabled&&<label>生理予定まで（日）<input type="number" min="0" value={period} onChange={e=>setPeriod(e.target.value)}/></label>}</div>}<button className="primary" disabled={!mood} onClick={save}>{saved?'保存しました':'この状態を保存'}</button></section>
    {state.checkins.length>0&&<section className="daily-bridges"><button onClick={onFortune}><b>今日の一枚</b><span>別の角度から今日の自分を見る →</span></button><button onClick={onTree}><b>今日、印象に残った人はいましたか？</b><span>My Treeに一言を残す（スキップできます） →</span></button></section>}
    <section className="summary-card"><div className="section-title"><Sparkles size={18}/><h2>今日のあなた</h2></div><p>{buildTodaySummary(state,displayDate)}</p><span className="meta">{timeBand}の状態と直近の記録から</span></section>
    {active.length>0&&<section><div className="section-title"><h2>やってみていること</h2></div>{active.map(a=><div className="active-action" key={a.id}><span>{a.title}</span><button className="small-button" onClick={()=>onComplete(a.id)}>できた</button></div>)}</section>}
    <section><div className="section-title"><div><p className="eyebrow">{state.checkins.length?'あなたの状態から選びました':'まずは今日の状態から'}</p><h2>今日のおすすめ</h2></div></div>{state.checkins.length?<div className="action-list">{recommendations.map(r=><ActionCard key={r.action.id} item={r} onOpen={()=>onOpenAction(r)}/>)}</div>:<p className="empty">気分をひとつ教えてくれたら、今日のあなたに合いそうなことを一緒に探せます。</p>}</section>
    <section><p className="eyebrow">今日は、自分のために何する？</p><div className="intent-grid">{['整える','楽しむ','学ぶ','休む'].map((x,i)=><button key={x} onClick={()=>onIntent(x)}><b>{['🌿','♫','📖','☾'][i]}</b>{x}</button>)}<button onClick={onTalk}><b><MessageCircle size={23}/></b>話す</button><button className="do-nothing" onClick={()=>onIntent('何もしない')}><b>○</b>今日は何もしない</button></div></section>
    {timeBand==='夜'&&reflection.map(a=><section className="reflection" key={a.id}><p className="eyebrow">夜の振り返り</p><h2>「{a.title}」はどうだった？</h2><div>{([['great','😍 よかった'],['okay','🙂 まあまあ'],['same','😐 変わらない'],['bad','🙅 合わなかった']] as [FeedbackRating,string][]).map(([r,l])=><button key={r} onClick={()=>onFeedback(a.id,a.actionId,r)}>{l}</button>)}</div></section>)}
  </main>;
}
