/* oxlint-disable jsx-a11y/prefer-tag-over-role -- SVG is the semantic data visualization for the relationship tree */
import { jstDate } from '@/lib/fortune/engine';
import { useState } from 'react';
import { ArrowLeft,Plus,X } from 'lucide-react';
import type { TreeCategory,TreeLeaf,TreeMeaningTag } from '@/types';
const categories:Record<TreeCategory,string>={family:'家族',friend:'友達',love:'恋愛',work:'仕事',learning:'学び',other:'その他'};
/** A name fits the leaf at four characters; a longer one is marked as cut, so 友だち10 never reads as 友だち1. */
/* Up to two lines inside the leaf (「冷蔵庫 / くん」), so short names are no longer cut after three characters. */
const leafLines=(name:string)=>{const chars=Array.from(new Intl.Segmenter('ja',{granularity:'grapheme'}).segment(name),part=>part.segment);if(chars.length<=4)return[name];if(chars.length<=8){const half=Math.ceil(chars.length/2);return[chars.slice(0,half).join(''),chars.slice(half).join('')]}return[chars.slice(0,4).join(''),`${chars.slice(4,7).join('')}…`]};
/* When this leaf was last written to (its existing updatedAt): 今日 / 昨日 / 3日前. */
const lastTouched=(iso:string,now=new Date())=>{if(!Number.isFinite(Date.parse(iso)))return'';const days=Math.round((Date.parse(jstDate(now))-Date.parse(jstDate(new Date(iso))))/86400000);if(days<=0)return'今日';if(days===1)return'昨日';if(days<31)return`${days}日前`;return new Date(iso).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'})};
const tags:Record<TreeMeaningTag,string>={precious:'大切な人',energizing:'元気をくれる人',calming:'落ち着く人',grow_together:'一緒に成長したい人',admire:'憧れている人',supportive:'支えてくれた人',curious:'もっと知りたい人',fun:'一緒にいると楽しい人'};
export function TreeScreen({leaves,onBack,onAdd,onUpdate,onRemove,onReflect,onTrack,onTalk}:{leaves:TreeLeaf[];onBack:()=>void;onRemove:(id:string)=>void;onAdd:(v:{name:string;category:TreeCategory;meaningTags:TreeMeaningTag[];note:string})=>void;onUpdate:(id:string,p:Partial<TreeLeaf>)=>void;onReflect:(id:string,t:string)=>void;onTalk:(leaf:TreeLeaf)=>void;onTrack:(n:'tree_add_start'|'tree_leaf_open'|'tree_leaf_edit'|'tree_archive'|'tree_reflection_add',p?:Record<string,string|number|boolean>)=>void}){
 const [adding,setAdding]=useState(false),[editing,setEditing]=useState<string>(),[confirmRemove,setConfirmRemove]=useState(false),[selectedSnapshot,setSelected]=useState<TreeLeaf>(),[name,setName]=useState(''),[category,setCategory]=useState<TreeCategory>('friend'),[meaning,setMeaning]=useState<TreeMeaningTag[]>([]),[note,setNote]=useState(''),[reflection,setReflection]=useState('');const active=leaves.filter(l=>l.status==='active');const memories=leaves.filter(l=>l.status==='memory');const selected=leaves.find(leaf=>leaf.id===selectedSnapshot?.id&&leaf.status!=='removed');
 const closeForm=()=>{setAdding(false);setEditing(undefined);setName('');setCategory('friend');setMeaning([]);setNote('')};
 const submit=()=>{if(!name.trim())return;if(editing){onUpdate(editing,{name:name.trim(),category,meaningTags:meaning,note:note.trim()});onTrack('tree_leaf_edit');}else onAdd({name:name.trim(),category,meaningTags:meaning,note:note.trim()});closeForm()};
 const startEdit=(leaf:TreeLeaf)=>{setName(leaf.name);setCategory(leaf.category);setMeaning(leaf.meaningTags);setNote(leaf.note);setEditing(leaf.id);setConfirmRemove(false);setSelected(undefined)};
 return <main className="screen tree"><button className="back" onClick={onBack}><ArrowLeft size={18}/> Myへ</button><header><div><p className="eyebrow">私をつくってきた、人とのつながり。</p><h1>My Tree</h1></div><button className="tree-add" aria-label="人を追加" onClick={()=>{setAdding(true);onTrack('tree_add_start')}}><Plus/></button></header>
 <p className="tree-intro">大切な人、その人との関係や思い出を、自分のために残しておく場所です。相手への通知はありません。</p><section className="tree-canvas"><svg viewBox="0 0 360 330" role="img" aria-label={`わたしを中心に${active.length}人がつながる木`}><path className="trunk" d="M180 300 C178 235 184 180 180 116"/>{active.slice(0,10).map((l,i)=>{const side=i%2?-1:1,x=180+side*(62+(i%3)*18),y=245-Math.floor(i/2)*45;return <g key={l.id} className="branch"><title>{l.name}</title><path d={`M180 ${Math.min(270,y+28)} Q ${x-side*30} ${y+15} ${x} ${y}`}/><circle cx={x} cy={y} r="26"/><text x={x} y={y+4}>{leafLines(l.name).map((line,n,all)=><tspan key={n} x={x} y={all.length===1?y+4:y-3+n*14}>{line}</tspan>)}</text></g>})}<circle className="self" cx="180" cy="287" r="34"/><text className="self-label" x="180" y="291">わたし</text></svg>{active.length>10&&<p className="tree-more">木には10人まで描いています。ほかの{active.length-10}人は、下の一覧にいます。</p>}{!active.length&&<p className="tree-empty">最初の葉を一枚、育ててみませんか。<br/>人を管理するためではなく、自分を知るための木です。</p>}</section>
 <div className="leaf-list">{active.map(l=><button key={l.id} onClick={()=>{setSelected(l);onTrack('tree_leaf_open',{leafAgeDays:Math.floor((Date.now()-new Date(l.createdAt).getTime())/86400000)})}}><span>●</span><div><b>{l.name}</b><small>{[categories[l.category],l.meaningTags.map(t=>tags[t]).join('、')].filter(Boolean).join(' ・ ')}</small></div><small className="leaf-updated">{lastTouched(l.updatedAt)}</small></button>)}</div>
 {memories.length>0&&<details><summary>思い出の葉（{memories.length}）</summary><div className="leaf-list">{memories.map(leaf=><button key={leaf.id} onClick={()=>{setSelected(leaf);onTrack('tree_leaf_open',{leafAgeDays:Math.floor((Date.now()-new Date(leaf.createdAt).getTime())/86400000)})}}><span>●</span><div><b>{leaf.name}</b><small>{categories[leaf.category]}</small></div></button>)}</div></details>}
 {(adding||editing)&&<div className="modal-backdrop"><section className="sheet tree-form"><button className="close" aria-label="閉じる" onClick={closeForm}><X/></button><h2>{editing?'この葉を編集する':'葉を一枚追加する'}</h2><label>名前／ニックネーム<input value={name} onChange={e=>setName(e.target.value)} maxLength={30}/></label><label>カテゴリ<select value={category} onChange={e=>setCategory(e.target.value as TreeCategory)}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><fieldset><legend>この人はあなたにとって？（複数選択可）</legend><div className="meaning-tags">{Object.entries(tags).map(([k,v])=><button type="button" className={meaning.includes(k as TreeMeaningTag)?'selected':''} key={k} onClick={()=>setMeaning(x=>x.includes(k as TreeMeaningTag)?x.filter(t=>t!==k):[...x,k as TreeMeaningTag])}>{v}</button>)}</div></fieldset><label>自分のための一言<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={160}/></label><button className="primary" disabled={!name.trim()} onClick={submit}>{editing?'保存する':'木に追加する'}</button></section></div>}
 {selected&&<div className="modal-backdrop"><section className="sheet leaf-detail"><button className="close" aria-label="閉じる" onClick={()=>{setSelected(undefined);setConfirmRemove(false)}}><X/></button><p className="eyebrow">{categories[selected.category]}</p><h2>{selected.name}</h2><div className="meaning-tags read-only">{selected.meaningTags.map(t=><span key={t}>{tags[t]}</span>)}</div>{selected.note&&<p>{selected.note}</p>}<div className="tree-timeline"><p className="meta">最初の記録：{new Date(selected.createdAt).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo'})}</p>{selected.reflections.map(item=><article key={item.id}><small>{new Date(item.createdAt).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo'})}</small><p>{item.text}</p></article>)}</div><button className="text-button" onClick={()=>onTalk(selected)}>この人のことをCamelliaに話す</button><label>今日、心に残ったこと<textarea value={reflection} onChange={e=>setReflection(e.target.value)} maxLength={200}/></label><button className="secondary-button" disabled={!reflection.trim()} onClick={()=>{onReflect(selected.id,reflection.trim());setReflection('')}}>一言を残す</button>{selected.status==='active'&&<button className="memory-link" onClick={()=>{onUpdate(selected.id,{status:'memory'});onTrack('tree_archive');setSelected(undefined)}}>思い出の葉として残す</button>}<div className="leaf-manage"><button className="text-button" onClick={()=>startEdit(selected)}>編集する</button><button className="text-button danger-link" onClick={()=>setConfirmRemove(true)}>削除する</button></div>{confirmRemove&&<div className="leaf-remove" role="alertdialog" aria-label="葉の削除"><p>{selected.name}さんの葉を削除しますか？名前・メモ・残した一言が消え、元に戻せません。</p><div className="sheet-actions"><button onClick={()=>setConfirmRemove(false)}>やめる</button><button className="danger-button" onClick={()=>{onRemove(selected.id);setConfirmRemove(false);setSelected(undefined)}}>削除する</button></div></div>}</section></div>}
 </main>
}
